title: InvesClub
name: InvesClub
user_description: investasi untuk masa depan
notes_url: "inves.club"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: InvesClub
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://inves.club" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /profile/:title

# disqus:
#  shortname: invesclub-kalau-udah-bikin

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /company/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
